=== Hchewai/xml-assessment2/resources/xml-car-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- W3C Schema generated by XMLSpy v2026 rel. 2 (x64) (https://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="https://www.w3.org/2001/XMLSchema.xsd">
	<xs:element name="classic-cars">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="vehicle" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute ref="xsi:noNamespaceSchemaLocation" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="company">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="FCA Italy"/>
				<xs:enumeration value="Honda"/>
				<xs:enumeration value="Mercedes-Benz"/>
				<xs:enumeration value="Toyota"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="country">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="Germany"/>
				<xs:enumeration value="Italy"/>
				<xs:enumeration value="Japan"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="model" type="xs:string"/>
	<xs:element name="price">
		<xs:simpleType>
			<xs:restriction base="xs:short">
				<xs:enumeration value="12000"/>
				<xs:enumeration value="15000"/>
				<xs:enumeration value="17000"/>
				<xs:enumeration value="2000"/>
				<xs:enumeration value="20000"/>
				<xs:enumeration value="23000"/>
				<xs:enumeration value="25000"/>
				<xs:enumeration value="27000"/>
				<xs:enumeration value="3000"/>
				<xs:enumeration value="5000"/>
				<xs:enumeration value="6000"/>
				<xs:enumeration value="8000"/>
				<xs:enumeration value="9000"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="vehicle">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="model"/>
				<xs:element ref="country"/>
				<xs:element ref="company"/>
				<xs:element ref="price"/>
				<xs:element ref="year"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="year">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="1953"/>
				<xs:enumeration value="1982"/>
				<xs:enumeration value="1986"/>
				<xs:enumeration value="1993"/>
				<xs:enumeration value="1994"/>
				<xs:enumeration value="1997"/>
				<xs:enumeration value="2000"/>
				<xs:enumeration value="2003"/>
				<xs:enumeration value="2008"/>
				<xs:enumeration value="2018"/>
				<xs:enumeration value="2022"/>
				<xs:enumeration value="2025"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
</xs:schema>

=== Hchewai/xml-assessment2/resources/cars.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- must contain model, country, company, price, year-->
<!-- needs 15 cars-->
<?xml-stylesheet type="text/xsl" href="file:///C:/laragon/www/XML-unit/xml-assessment2/resources/design.xslt"?>
<classic-cars xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/laragon/www/XML-unit/xml-assessment2/resources/xml-car-schema.xsd">
	<!--1st from Honda-->
	<vehicle>
		<model>Integra</model>
		<country>Japan</country>
		<company>Honda</company>
		<price>$5000</price>
		<year>1986</year>
	</vehicle>
	<!--2nd-->
	<vehicle>
		<model>ADX</model>
		<country>Japan</country>
		<company>Honda</company>
		<price>$8000</price>
		<year>2025</year>
	</vehicle>
	<!--3rd-->
	<vehicle>
		<model>MDX</model>
		<country>Japan</country>
		<company>Honda</company>
		<price>$6000</price>
		<year>2000</year>
	</vehicle>
	<!--4th-->
	<vehicle>
		<model>MDX</model>
		<country>Japan</country>
		<company>Honda</company>
		<price>$6000</price>
		<year>2000</year>
	</vehicle>
	<!--5th Alfa Romeo-->
	<vehicle>
		<model>Alfa Romeo MiTo</model>
		<country>Italy</country>
		<company>FCA Italy</company>
		<price>$9000</price>
		<year>2008</year>
	</vehicle>
	<!--6th-->
	<vehicle>
		<model>Alfa Romeo Kamal</model>
		<country>Italy</country>
		<company>FCA Italy</company>
		<price>$3000</price>
		<year>2003</year>
	</vehicle>
	<!--7th-->
	<vehicle>
		<model>Alfa Romeo BAT</model>
		<country>Italy</country>
		<company>FCA Italy</company>
		<price>$12000</price>
		<year>1953</year>
	</vehicle>
	<!--8th-->
	<vehicle>
		<model>Alfa Romeo Tonale</model>
		<country>Italy</country>
		<company>FCA Italy</company>
		<price>$15000</price>
		<year>2022</year>
	</vehicle>
	<!--9th Mercedes-->
	<vehicle>
		<model>A-Class C-segment/subcompact executive hatchback</model>
		<country>Germany</country>
		<company>Mercedes-Benz</company>
		<price>$20000</price>
		<year>1997</year>
	</vehicle>
	<!-- 10th-->
	<vehicle>
		<model>A-Class C-Segment Subcompact Executive Sedan</model>
		<country>Germany</country>
		<company>Mercedes-Benz</company>
		<price>$23000</price>
		<year>2018</year>
	</vehicle>
	<!-- 11th -->
	<vehicle>
		<model>CLA C-segment/subcompact executive fastback sedan</model>
		<country>Germany</country>
		<company>Mercedes-Benz</company>
		<price>$25000</price>
		<year>2018</year>
	</vehicle>
	<!--12th-->
	<vehicle>
		<model>C-Class D-segment/compact executive sedan</model>
		<country>Germany</country>
		<company>Mercedes-Benz</company>
		<price>$27000</price>
		<year>1993</year>
	</vehicle>
	<!--13th Toyota-->
	<vehicle>
		<model>Avalon</model>
		<country>Japan</country>
		<company>Toyota</company>
		<price>$15000</price>
		<year>1994</year>
	</vehicle>
	<!--14th-->
	<vehicle>
		<model>bZ3</model>
		<country>Japan</country>
		<company>Toyota</company>
		<price>$17000</price>
		<year>2022</year>
	</vehicle>
	<!--15th-->
	<vehicle>
		<model>Camry</model>
		<country>Japan</country>
		<company>Toyota</company>
		<price>$2000</price>
		<year>1982</year>
	</vehicle>
</classic-cars>
